# Generated by Django 4.2.15 on 2025-02-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="type",
            field=models.CharField(
                choices=[
                    ("type_1", "Type_1"),
                    ("type_2", "Type_2"),
                    ("type_3", "Type_3"),
                    ("type_4", "Type_4"),
                ],
                default="type_1",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
