# Generated by Django 4.2.15 on 2024-11-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0003_message_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="content",
        ),
        migrations.RemoveField(
            model_name="message",
            name="type",
        ),
        migrations.AddField(
            model_name="message",
            name="question",
            field=models.TextField(blank=True, max_length=8000),
        ),
        migrations.AddField(
            model_name="message",
            name="response",
            field=models.TextField(max_length=8000, null=True),
        ),
    ]
